<script src="{{ asset('admin_panel/js/vendor/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/moment.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/fullcalendar.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/bootstrap-notify.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/select2.full.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/dropzone.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/nouislider.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/jquery.barrating.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/cropper.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/typeahead.bundle.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/mousetrap.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/dore-plugins/select.from.library.js') }}"></script>
<script src="{{ asset('admin_panel/js/dore.script.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/datatables.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/perfect-scrollbar.min.js') }}"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
<script src="{{ asset('admin_panel/js/vendor/ckeditor5-build-classic/ckeditor.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/jquery.smartWizard.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/jquery.validate/jquery.validate.min.js') }}"></script>
<script src="{{ asset('admin_panel/js/vendor/jquery.validate/additional-methods.min.js') }}"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{{ asset('admin_panel/js/scripts.js') }}"></script>
<script src="{{ asset('admin_panel/js/demo.js') }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@include('includes.notifications')
